name: Pytest Tests
env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  WALLET_DEFAULT_DB: ${{ secrets.WALLET_DEFAULT_DB }}
  WALLET_RECORDS_COLLECTION: ${{ secrets.WALLET_RECORDS_COLLECTION }}
on:
  pull_request:
    branches: [ main ]
jobs:
  pytest-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '7.0'

      - name: Run Pytest tests
        run: python -m pytest tests/ --html=pytest-report.html

      - name: Upload html report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: pytest-report
          retention-days: 30